### ISSUE TITLE
“Revert” button is enabled when there’s nothing to revert

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#517]
1\. Go to the “Market” (or equivalent) page for a snap.
2\. Look at the “Revert” and “Apply” buttons.

What you see:
- “Apply” is disabled because there’s nothing to apply.
- “Revert” is enabled even though there’s nothing to revert.

What you should see:
- “Revert” is disabled because there’s nothing to revert.

**Comment by therealjuan** [comment]
Fixed now on `Apply` CTA

**Comment by matthewpaulthomas** [comment]
I guess by “`Apply` CTA” you mean the “Save” button? I mentioned that, in the initial report, only to contrast the “Save” button’s correct behavior with the “Revert” button’s incorrect behavior. (Which suggests that the necessary logic is already in the code, it just needs expanding from one button to two.)

Unfortunately the problem still exists, both on production and on staging.

![517-revert-button](https://user-images.githubusercontent.com/19801137/42285550-d44ab61e-7fa7-11e8-9a15-af951ab953ae.png)
